[package]
name = "relog"
version = "0.1.0"
authors = ["Michael Krolikowski <mkroli@yahoo.de>"]
description = "replays logfiles"

[dependencies]
error-chain = "0.12"
clap = "2"
nom = "5"
regex = "1"
time = "0.1"
